version: "3.8"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  api:
    container_name: node_assignment
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
      - .:/usr/src/server
      - /usr/src/server/node_modules

  client:
    container_name: node_assignment_client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  data: {}
